// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	model "github.com/weeranieb/boonmafarm-backend/src/internal/model"

	repository "github.com/weeranieb/boonmafarm-backend/src/internal/repository"
)

// MockActivePondRepository is an autogenerated mock type for the ActivePondRepository type
type MockActivePondRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, activePond
func (_m *MockActivePondRepository) Create(ctx context.Context, activePond *model.ActivePond) error {
	ret := _m.Called(ctx, activePond)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.ActivePond) error); ok {
		r0 = rf(ctx, activePond)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetActiveByPondID provides a mock function with given fields: ctx, pondId
func (_m *MockActivePondRepository) GetActiveByPondID(ctx context.Context, pondId int) (*model.ActivePond, error) {
	ret := _m.Called(ctx, pondId)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveByPondID")
	}

	var r0 *model.ActivePond
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*model.ActivePond, error)); ok {
		return rf(ctx, pondId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *model.ActivePond); ok {
		r0 = rf(ctx, pondId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ActivePond)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, pondId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, activePond
func (_m *MockActivePondRepository) Update(ctx context.Context, activePond *model.ActivePond) error {
	ret := _m.Called(ctx, activePond)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.ActivePond) error); ok {
		r0 = rf(ctx, activePond)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithTx provides a mock function with given fields: tx
func (_m *MockActivePondRepository) WithTx(tx *gorm.DB) repository.ActivePondRepository {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 repository.ActivePondRepository
	if rf, ok := ret.Get(0).(func(*gorm.DB) repository.ActivePondRepository); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.ActivePondRepository)
		}
	}

	return r0
}

// NewMockActivePondRepository creates a new instance of MockActivePondRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockActivePondRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockActivePondRepository {
	mock := &MockActivePondRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
