// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	model "github.com/weeranieb/boonmafarm-backend/src/internal/model"

	repository "github.com/weeranieb/boonmafarm-backend/src/internal/repository"
)

// MockActivityRepository is an autogenerated mock type for the ActivityRepository type
type MockActivityRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, activity
func (_m *MockActivityRepository) Create(ctx context.Context, activity *model.Activity) error {
	ret := _m.Called(ctx, activity)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Activity) error); ok {
		r0 = rf(ctx, activity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListByPondID provides a mock function with given fields: ctx, pondId
func (_m *MockActivityRepository) ListByPondID(ctx context.Context, pondId int) ([]repository.ActivityListRow, error) {
	ret := _m.Called(ctx, pondId)

	if len(ret) == 0 {
		panic("no return value specified for ListByPondID")
	}

	var r0 []repository.ActivityListRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]repository.ActivityListRow, error)); ok {
		return rf(ctx, pondId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []repository.ActivityListRow); ok {
		r0 = rf(ctx, pondId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.ActivityListRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, pondId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListRecentByClientID provides a mock function with given fields: ctx, clientId, limit
func (_m *MockActivityRepository) ListRecentByClientID(ctx context.Context, clientId *int, limit int) ([]repository.ActivityFeedRow, error) {
	ret := _m.Called(ctx, clientId, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListRecentByClientID")
	}

	var r0 []repository.ActivityFeedRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *int, int) ([]repository.ActivityFeedRow, error)); ok {
		return rf(ctx, clientId, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *int, int) []repository.ActivityFeedRow); ok {
		r0 = rf(ctx, clientId, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.ActivityFeedRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *int, int) error); ok {
		r1 = rf(ctx, clientId, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SumAdditionalCostsByActivityIDs provides a mock function with given fields: ctx, activityIds
func (_m *MockActivityRepository) SumAdditionalCostsByActivityIDs(ctx context.Context, activityIds []int) ([]repository.AdditionalCostTotalRow, error) {
	ret := _m.Called(ctx, activityIds)

	if len(ret) == 0 {
		panic("no return value specified for SumAdditionalCostsByActivityIDs")
	}

	var r0 []repository.AdditionalCostTotalRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int) ([]repository.AdditionalCostTotalRow, error)); ok {
		return rf(ctx, activityIds)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int) []repository.AdditionalCostTotalRow); ok {
		r0 = rf(ctx, activityIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.AdditionalCostTotalRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int) error); ok {
		r1 = rf(ctx, activityIds)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SumSellDetailsByActivityIDs provides a mock function with given fields: ctx, activityIds
func (_m *MockActivityRepository) SumSellDetailsByActivityIDs(ctx context.Context, activityIds []int) ([]repository.SellTotalRow, error) {
	ret := _m.Called(ctx, activityIds)

	if len(ret) == 0 {
		panic("no return value specified for SumSellDetailsByActivityIDs")
	}

	var r0 []repository.SellTotalRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int) ([]repository.SellTotalRow, error)); ok {
		return rf(ctx, activityIds)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int) []repository.SellTotalRow); ok {
		r0 = rf(ctx, activityIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.SellTotalRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int) error); ok {
		r1 = rf(ctx, activityIds)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WithTx provides a mock function with given fields: tx
func (_m *MockActivityRepository) WithTx(tx *gorm.DB) repository.ActivityRepository {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 repository.ActivityRepository
	if rf, ok := ret.Get(0).(func(*gorm.DB) repository.ActivityRepository); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.ActivityRepository)
		}
	}

	return r0
}

// NewMockActivityRepository creates a new instance of MockActivityRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockActivityRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockActivityRepository {
	mock := &MockActivityRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
