// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	model "github.com/weeranieb/boonmafarm-backend/src/internal/model"

	repository "github.com/weeranieb/boonmafarm-backend/src/internal/repository"
)

// MockAdditionalCostRepository is an autogenerated mock type for the AdditionalCostRepository type
type MockAdditionalCostRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, ac
func (_m *MockAdditionalCostRepository) Create(ctx context.Context, ac *model.AdditionalCost) error {
	ret := _m.Called(ctx, ac)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdditionalCost) error); ok {
		r0 = rf(ctx, ac)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateBatch provides a mock function with given fields: ctx, items
func (_m *MockAdditionalCostRepository) CreateBatch(ctx context.Context, items []*model.AdditionalCost) error {
	ret := _m.Called(ctx, items)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*model.AdditionalCost) error); ok {
		r0 = rf(ctx, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithTx provides a mock function with given fields: tx
func (_m *MockAdditionalCostRepository) WithTx(tx *gorm.DB) repository.AdditionalCostRepository {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 repository.AdditionalCostRepository
	if rf, ok := ret.Get(0).(func(*gorm.DB) repository.AdditionalCostRepository); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.AdditionalCostRepository)
		}
	}

	return r0
}

// NewMockAdditionalCostRepository creates a new instance of MockAdditionalCostRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdditionalCostRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdditionalCostRepository {
	mock := &MockAdditionalCostRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
