// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	model "github.com/weeranieb/boonmafarm-backend/src/internal/model"

	repository "github.com/weeranieb/boonmafarm-backend/src/internal/repository"

	time "time"
)

// MockDailyLogRepository is an autogenerated mock type for the DailyLogRepository type
type MockDailyLogRepository struct {
	mock.Mock
}

// HardDeleteByActivePondAndDates provides a mock function with given fields: ctx, activePondId, dates
func (_m *MockDailyLogRepository) HardDeleteByActivePondAndDates(ctx context.Context, activePondId int, dates []time.Time) error {
	ret := _m.Called(ctx, activePondId, dates)

	if len(ret) == 0 {
		panic("no return value specified for HardDeleteByActivePondAndDates")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, []time.Time) error); ok {
		r0 = rf(ctx, activePondId, dates)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HardDeleteByIDs provides a mock function with given fields: ctx, ids
func (_m *MockDailyLogRepository) HardDeleteByIDs(ctx context.Context, ids []int) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for HardDeleteByIDs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []int) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListByActivePondAndMonth provides a mock function with given fields: ctx, activePondId, start, end
func (_m *MockDailyLogRepository) ListByActivePondAndMonth(ctx context.Context, activePondId int, start time.Time, end time.Time) ([]*model.DailyLog, error) {
	ret := _m.Called(ctx, activePondId, start, end)

	if len(ret) == 0 {
		panic("no return value specified for ListByActivePondAndMonth")
	}

	var r0 []*model.DailyLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, time.Time, time.Time) ([]*model.DailyLog, error)); ok {
		return rf(ctx, activePondId, start, end)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, time.Time, time.Time) []*model.DailyLog); ok {
		r0 = rf(ctx, activePondId, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.DailyLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, time.Time, time.Time) error); ok {
		r1 = rf(ctx, activePondId, start, end)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListIDAndFeedDateByActivePondRange provides a mock function with given fields: ctx, activePondId, min, max
func (_m *MockDailyLogRepository) ListIDAndFeedDateByActivePondRange(ctx context.Context, activePondId int, min time.Time, max time.Time) ([]repository.DailyLogIDFeedDate, error) {
	ret := _m.Called(ctx, activePondId, min, max)

	if len(ret) == 0 {
		panic("no return value specified for ListIDAndFeedDateByActivePondRange")
	}

	var r0 []repository.DailyLogIDFeedDate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, time.Time, time.Time) ([]repository.DailyLogIDFeedDate, error)); ok {
		return rf(ctx, activePondId, min, max)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, time.Time, time.Time) []repository.DailyLogIDFeedDate); ok {
		r0 = rf(ctx, activePondId, min, max)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.DailyLogIDFeedDate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, time.Time, time.Time) error); ok {
		r1 = rf(ctx, activePondId, min, max)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upsert provides a mock function with given fields: ctx, logs
func (_m *MockDailyLogRepository) Upsert(ctx context.Context, logs []*model.DailyLog) error {
	ret := _m.Called(ctx, logs)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*model.DailyLog) error); ok {
		r0 = rf(ctx, logs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithTx provides a mock function with given fields: tx
func (_m *MockDailyLogRepository) WithTx(tx *gorm.DB) repository.DailyLogRepository {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 repository.DailyLogRepository
	if rf, ok := ret.Get(0).(func(*gorm.DB) repository.DailyLogRepository); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.DailyLogRepository)
		}
	}

	return r0
}

// NewMockDailyLogRepository creates a new instance of MockDailyLogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDailyLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDailyLogRepository {
	mock := &MockDailyLogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
