// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	model "github.com/weeranieb/boonmafarm-backend/src/internal/model"
)

// MockFarmRepository is an autogenerated mock type for the FarmRepository type
type MockFarmRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: farm
func (_m *MockFarmRepository) Create(farm *model.Farm) error {
	ret := _m.Called(farm)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Farm) error); ok {
		r0 = rf(farm)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByCodeAndClientId provides a mock function with given fields: code, clientId
func (_m *MockFarmRepository) GetByCodeAndClientId(code string, clientId int) (*model.Farm, error) {
	ret := _m.Called(code, clientId)

	if len(ret) == 0 {
		panic("no return value specified for GetByCodeAndClientId")
	}

	var r0 *model.Farm
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) (*model.Farm, error)); ok {
		return rf(code, clientId)
	}
	if rf, ok := ret.Get(0).(func(string, int) *model.Farm); ok {
		r0 = rf(code, clientId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Farm)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(code, clientId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *MockFarmRepository) GetByID(id int) (*model.Farm, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Farm
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*model.Farm, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *model.Farm); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Farm)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByNameAndClientId provides a mock function with given fields: name, clientId
func (_m *MockFarmRepository) GetByNameAndClientId(name string, clientId int) (*model.Farm, error) {
	ret := _m.Called(name, clientId)

	if len(ret) == 0 {
		panic("no return value specified for GetByNameAndClientId")
	}

	var r0 *model.Farm
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) (*model.Farm, error)); ok {
		return rf(name, clientId)
	}
	if rf, ok := ret.Get(0).(func(string, int) *model.Farm); ok {
		r0 = rf(name, clientId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Farm)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(name, clientId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByClientId provides a mock function with given fields: clientId
func (_m *MockFarmRepository) ListByClientId(clientId int) ([]*model.Farm, error) {
	ret := _m.Called(clientId)

	if len(ret) == 0 {
		panic("no return value specified for ListByClientId")
	}

	var r0 []*model.Farm
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]*model.Farm, error)); ok {
		return rf(clientId)
	}
	if rf, ok := ret.Get(0).(func(int) []*model.Farm); ok {
		r0 = rf(clientId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Farm)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(clientId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: farm
func (_m *MockFarmRepository) Update(farm *model.Farm) error {
	ret := _m.Called(farm)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Farm) error); ok {
		r0 = rf(farm)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockFarmRepository creates a new instance of MockFarmRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFarmRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFarmRepository {
	mock := &MockFarmRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
