// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/weeranieb/boonmafarm-backend/src/internal/model"
)

// MockFeedCollectionRepository is an autogenerated mock type for the FeedCollectionRepository type
type MockFeedCollectionRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, feedCollection
func (_m *MockFeedCollectionRepository) Create(ctx context.Context, feedCollection *model.FeedCollection) error {
	ret := _m.Called(ctx, feedCollection)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.FeedCollection) error); ok {
		r0 = rf(ctx, feedCollection)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByClientIdAndName provides a mock function with given fields: clientId, name
func (_m *MockFeedCollectionRepository) GetByClientIdAndName(clientId int, name string) (*model.FeedCollection, error) {
	ret := _m.Called(clientId, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByClientIdAndName")
	}

	var r0 *model.FeedCollection
	var r1 error
	if rf, ok := ret.Get(0).(func(int, string) (*model.FeedCollection, error)); ok {
		return rf(clientId, name)
	}
	if rf, ok := ret.Get(0).(func(int, string) *model.FeedCollection); ok {
		r0 = rf(clientId, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.FeedCollection)
		}
	}

	if rf, ok := ret.Get(1).(func(int, string) error); ok {
		r1 = rf(clientId, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *MockFeedCollectionRepository) GetByID(id int) (*model.FeedCollection, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.FeedCollection
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*model.FeedCollection, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *model.FeedCollection); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.FeedCollection)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPage provides a mock function with given fields: clientId, page, pageSize, orderBy, keyword
func (_m *MockFeedCollectionRepository) GetPage(clientId int, page int, pageSize int, orderBy string, keyword string) ([]*model.FeedCollectionPage, int64, error) {
	ret := _m.Called(clientId, page, pageSize, orderBy, keyword)

	if len(ret) == 0 {
		panic("no return value specified for GetPage")
	}

	var r0 []*model.FeedCollectionPage
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int, int, string, string) ([]*model.FeedCollectionPage, int64, error)); ok {
		return rf(clientId, page, pageSize, orderBy, keyword)
	}
	if rf, ok := ret.Get(0).(func(int, int, int, string, string) []*model.FeedCollectionPage); ok {
		r0 = rf(clientId, page, pageSize, orderBy, keyword)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.FeedCollectionPage)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, int, string, string) int64); ok {
		r1 = rf(clientId, page, pageSize, orderBy, keyword)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(int, int, int, string, string) error); ok {
		r2 = rf(clientId, page, pageSize, orderBy, keyword)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: ctx, feedCollection
func (_m *MockFeedCollectionRepository) Update(ctx context.Context, feedCollection *model.FeedCollection) error {
	ret := _m.Called(ctx, feedCollection)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.FeedCollection) error); ok {
		r0 = rf(ctx, feedCollection)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockFeedCollectionRepository creates a new instance of MockFeedCollectionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFeedCollectionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFeedCollectionRepository {
	mock := &MockFeedCollectionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
