// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/weeranieb/boonmafarm-backend/src/internal/model"

	time "time"
)

// MockFeedPriceHistoryRepository is an autogenerated mock type for the FeedPriceHistoryRepository type
type MockFeedPriceHistoryRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, feedPriceHistory
func (_m *MockFeedPriceHistoryRepository) Create(ctx context.Context, feedPriceHistory *model.FeedPriceHistory) error {
	ret := _m.Called(ctx, feedPriceHistory)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.FeedPriceHistory) error); ok {
		r0 = rf(ctx, feedPriceHistory)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateBatch provides a mock function with given fields: ctx, feedPriceHistories
func (_m *MockFeedPriceHistoryRepository) CreateBatch(ctx context.Context, feedPriceHistories []*model.FeedPriceHistory) error {
	ret := _m.Called(ctx, feedPriceHistories)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*model.FeedPriceHistory) error); ok {
		r0 = rf(ctx, feedPriceHistories)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByFeedCollectionIdAndDate provides a mock function with given fields: feedCollectionId, priceUpdatedDate
func (_m *MockFeedPriceHistoryRepository) GetByFeedCollectionIdAndDate(feedCollectionId int, priceUpdatedDate time.Time) (*model.FeedPriceHistory, error) {
	ret := _m.Called(feedCollectionId, priceUpdatedDate)

	if len(ret) == 0 {
		panic("no return value specified for GetByFeedCollectionIdAndDate")
	}

	var r0 *model.FeedPriceHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(int, time.Time) (*model.FeedPriceHistory, error)); ok {
		return rf(feedCollectionId, priceUpdatedDate)
	}
	if rf, ok := ret.Get(0).(func(int, time.Time) *model.FeedPriceHistory); ok {
		r0 = rf(feedCollectionId, priceUpdatedDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.FeedPriceHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(int, time.Time) error); ok {
		r1 = rf(feedCollectionId, priceUpdatedDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *MockFeedPriceHistoryRepository) GetByID(id int) (*model.FeedPriceHistory, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.FeedPriceHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*model.FeedPriceHistory, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *model.FeedPriceHistory); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.FeedPriceHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByFeedCollectionId provides a mock function with given fields: feedCollectionId
func (_m *MockFeedPriceHistoryRepository) ListByFeedCollectionId(feedCollectionId int) ([]*model.FeedPriceHistory, error) {
	ret := _m.Called(feedCollectionId)

	if len(ret) == 0 {
		panic("no return value specified for ListByFeedCollectionId")
	}

	var r0 []*model.FeedPriceHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]*model.FeedPriceHistory, error)); ok {
		return rf(feedCollectionId)
	}
	if rf, ok := ret.Get(0).(func(int) []*model.FeedPriceHistory); ok {
		r0 = rf(feedCollectionId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.FeedPriceHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(feedCollectionId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, feedPriceHistory
func (_m *MockFeedPriceHistoryRepository) Update(ctx context.Context, feedPriceHistory *model.FeedPriceHistory) error {
	ret := _m.Called(ctx, feedPriceHistory)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.FeedPriceHistory) error); ok {
		r0 = rf(ctx, feedPriceHistory)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockFeedPriceHistoryRepository creates a new instance of MockFeedPriceHistoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFeedPriceHistoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFeedPriceHistoryRepository {
	mock := &MockFeedPriceHistoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
