// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	model "github.com/weeranieb/boonmafarm-backend/src/internal/model"
	gorm "gorm.io/gorm"

	repository "github.com/weeranieb/boonmafarm-backend/src/internal/repository"
)

// MockFishSizeGradeRepository is an autogenerated mock type for the FishSizeGradeRepository type
type MockFishSizeGradeRepository struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: id
func (_m *MockFishSizeGradeRepository) GetByID(id int) (*model.FishSizeGrade, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.FishSizeGrade
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*model.FishSizeGrade, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *model.FishSizeGrade); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.FishSizeGrade)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByIDs provides a mock function with given fields: ids
func (_m *MockFishSizeGradeRepository) GetByIDs(ids []int) ([]*model.FishSizeGrade, error) {
	ret := _m.Called(ids)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDs")
	}

	var r0 []*model.FishSizeGrade
	var r1 error
	if rf, ok := ret.Get(0).(func([]int) ([]*model.FishSizeGrade, error)); ok {
		return rf(ids)
	}
	if rf, ok := ret.Get(0).(func([]int) []*model.FishSizeGrade); ok {
		r0 = rf(ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.FishSizeGrade)
		}
	}

	if rf, ok := ret.Get(1).(func([]int) error); ok {
		r1 = rf(ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with no fields
func (_m *MockFishSizeGradeRepository) List() ([]*model.FishSizeGrade, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*model.FishSizeGrade
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*model.FishSizeGrade, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*model.FishSizeGrade); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.FishSizeGrade)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WithTx provides a mock function with given fields: tx
func (_m *MockFishSizeGradeRepository) WithTx(tx *gorm.DB) repository.FishSizeGradeRepository {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 repository.FishSizeGradeRepository
	if rf, ok := ret.Get(0).(func(*gorm.DB) repository.FishSizeGradeRepository); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.FishSizeGradeRepository)
		}
	}

	return r0
}

// NewMockFishSizeGradeRepository creates a new instance of MockFishSizeGradeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFishSizeGradeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFishSizeGradeRepository {
	mock := &MockFishSizeGradeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
