// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/weeranieb/boonmafarm-backend/src/internal/model"
)

// MockMerchantRepository is an autogenerated mock type for the MerchantRepository type
type MockMerchantRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, merchant
func (_m *MockMerchantRepository) Create(ctx context.Context, merchant *model.Merchant) error {
	ret := _m.Called(ctx, merchant)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Merchant) error); ok {
		r0 = rf(ctx, merchant)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockMerchantRepository) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByClientIdAndContactNumber provides a mock function with given fields: clientId, contactNumber
func (_m *MockMerchantRepository) GetByClientIdAndContactNumber(clientId int, contactNumber string) (*model.Merchant, error) {
	ret := _m.Called(clientId, contactNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetByClientIdAndContactNumber")
	}

	var r0 *model.Merchant
	var r1 error
	if rf, ok := ret.Get(0).(func(int, string) (*model.Merchant, error)); ok {
		return rf(clientId, contactNumber)
	}
	if rf, ok := ret.Get(0).(func(int, string) *model.Merchant); ok {
		r0 = rf(clientId, contactNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Merchant)
		}
	}

	if rf, ok := ret.Get(1).(func(int, string) error); ok {
		r1 = rf(clientId, contactNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *MockMerchantRepository) GetByID(id int) (*model.Merchant, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Merchant
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*model.Merchant, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *model.Merchant); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Merchant)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: clientId
func (_m *MockMerchantRepository) List(clientId int) ([]*model.Merchant, error) {
	ret := _m.Called(clientId)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*model.Merchant
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]*model.Merchant, error)); ok {
		return rf(clientId)
	}
	if rf, ok := ret.Get(0).(func(int) []*model.Merchant); ok {
		r0 = rf(clientId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Merchant)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(clientId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, merchant
func (_m *MockMerchantRepository) Update(ctx context.Context, merchant *model.Merchant) error {
	ret := _m.Called(ctx, merchant)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Merchant) error); ok {
		r0 = rf(ctx, merchant)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockMerchantRepository creates a new instance of MockMerchantRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMerchantRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMerchantRepository {
	mock := &MockMerchantRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
