// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	model "github.com/weeranieb/boonmafarm-backend/src/internal/model"

	repository "github.com/weeranieb/boonmafarm-backend/src/internal/repository"
)

// MockPondRepository is an autogenerated mock type for the PondRepository type
type MockPondRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, pond
func (_m *MockPondRepository) Create(ctx context.Context, pond *model.Pond) error {
	ret := _m.Called(ctx, pond)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Pond) error); ok {
		r0 = rf(ctx, pond)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateBatch provides a mock function with given fields: ctx, ponds
func (_m *MockPondRepository) CreateBatch(ctx context.Context, ponds []*model.Pond) error {
	ret := _m.Called(ctx, ponds)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*model.Pond) error); ok {
		r0 = rf(ctx, ponds)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockPondRepository) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByFarmIdAndName provides a mock function with given fields: farmId, name
func (_m *MockPondRepository) GetByFarmIdAndName(farmId int, name string) (*model.Pond, error) {
	ret := _m.Called(farmId, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByFarmIdAndName")
	}

	var r0 *model.Pond
	var r1 error
	if rf, ok := ret.Get(0).(func(int, string) (*model.Pond, error)); ok {
		return rf(farmId, name)
	}
	if rf, ok := ret.Get(0).(func(int, string) *model.Pond); ok {
		r0 = rf(farmId, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Pond)
		}
	}

	if rf, ok := ret.Get(1).(func(int, string) error); ok {
		r1 = rf(farmId, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *MockPondRepository) GetByID(id int) (*model.Pond, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Pond
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*model.Pond, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *model.Pond); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Pond)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByIDWithFarmAndActivePond provides a mock function with given fields: ctx, pondId
func (_m *MockPondRepository) GetByIDWithFarmAndActivePond(ctx context.Context, pondId int) (*repository.PondWithFarmAndActivePond, error) {
	ret := _m.Called(ctx, pondId)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDWithFarmAndActivePond")
	}

	var r0 *repository.PondWithFarmAndActivePond
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*repository.PondWithFarmAndActivePond, error)); ok {
		return rf(ctx, pondId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *repository.PondWithFarmAndActivePond); ok {
		r0 = rf(ctx, pondId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.PondWithFarmAndActivePond)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, pondId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByFarmId provides a mock function with given fields: farmId
func (_m *MockPondRepository) ListByFarmId(farmId int) ([]*model.Pond, error) {
	ret := _m.Called(farmId)

	if len(ret) == 0 {
		panic("no return value specified for ListByFarmId")
	}

	var r0 []*model.Pond
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]*model.Pond, error)); ok {
		return rf(farmId)
	}
	if rf, ok := ret.Get(0).(func(int) []*model.Pond); ok {
		r0 = rf(farmId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Pond)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(farmId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByFarmIdWithActivePond provides a mock function with given fields: ctx, farmId
func (_m *MockPondRepository) ListByFarmIdWithActivePond(ctx context.Context, farmId int) ([]*repository.PondWithFarmAndActivePond, error) {
	ret := _m.Called(ctx, farmId)

	if len(ret) == 0 {
		panic("no return value specified for ListByFarmIdWithActivePond")
	}

	var r0 []*repository.PondWithFarmAndActivePond
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*repository.PondWithFarmAndActivePond, error)); ok {
		return rf(ctx, farmId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*repository.PondWithFarmAndActivePond); ok {
		r0 = rf(ctx, farmId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*repository.PondWithFarmAndActivePond)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, farmId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, pond
func (_m *MockPondRepository) Update(ctx context.Context, pond *model.Pond) error {
	ret := _m.Called(ctx, pond)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Pond) error); ok {
		r0 = rf(ctx, pond)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithTx provides a mock function with given fields: tx
func (_m *MockPondRepository) WithTx(tx *gorm.DB) repository.PondRepository {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 repository.PondRepository
	if rf, ok := ret.Get(0).(func(*gorm.DB) repository.PondRepository); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.PondRepository)
		}
	}

	return r0
}

// NewMockPondRepository creates a new instance of MockPondRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPondRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPondRepository {
	mock := &MockPondRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
