// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	model "github.com/weeranieb/boonmafarm-backend/src/internal/model"
)

// MockPondRepository is an autogenerated mock type for the PondRepository type
type MockPondRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: pond
func (_m *MockPondRepository) Create(pond *model.Pond) error {
	ret := _m.Called(pond)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Pond) error); ok {
		r0 = rf(pond)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateBatch provides a mock function with given fields: ponds
func (_m *MockPondRepository) CreateBatch(ponds []*model.Pond) error {
	ret := _m.Called(ponds)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]*model.Pond) error); ok {
		r0 = rf(ponds)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *MockPondRepository) Delete(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByFarmIdAndCode provides a mock function with given fields: farmId, code
func (_m *MockPondRepository) GetByFarmIdAndCode(farmId int, code string) (*model.Pond, error) {
	ret := _m.Called(farmId, code)

	if len(ret) == 0 {
		panic("no return value specified for GetByFarmIdAndCode")
	}

	var r0 *model.Pond
	var r1 error
	if rf, ok := ret.Get(0).(func(int, string) (*model.Pond, error)); ok {
		return rf(farmId, code)
	}
	if rf, ok := ret.Get(0).(func(int, string) *model.Pond); ok {
		r0 = rf(farmId, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Pond)
		}
	}

	if rf, ok := ret.Get(1).(func(int, string) error); ok {
		r1 = rf(farmId, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *MockPondRepository) GetByID(id int) (*model.Pond, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Pond
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*model.Pond, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *model.Pond); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Pond)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByFarmId provides a mock function with given fields: farmId
func (_m *MockPondRepository) ListByFarmId(farmId int) ([]*model.Pond, error) {
	ret := _m.Called(farmId)

	if len(ret) == 0 {
		panic("no return value specified for ListByFarmId")
	}

	var r0 []*model.Pond
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]*model.Pond, error)); ok {
		return rf(farmId)
	}
	if rf, ok := ret.Get(0).(func(int) []*model.Pond); ok {
		r0 = rf(farmId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Pond)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(farmId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: pond
func (_m *MockPondRepository) Update(pond *model.Pond) error {
	ret := _m.Called(pond)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Pond) error); ok {
		r0 = rf(pond)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockPondRepository creates a new instance of MockPondRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPondRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPondRepository {
	mock := &MockPondRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
