// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	model "github.com/weeranieb/boonmafarm-backend/src/internal/model"

	repository "github.com/weeranieb/boonmafarm-backend/src/internal/repository"
)

// MockSellDetailRepository is an autogenerated mock type for the SellDetailRepository type
type MockSellDetailRepository struct {
	mock.Mock
}

// CreateBatch provides a mock function with given fields: ctx, details
func (_m *MockSellDetailRepository) CreateBatch(ctx context.Context, details []*model.SellDetail) error {
	ret := _m.Called(ctx, details)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*model.SellDetail) error); ok {
		r0 = rf(ctx, details)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithTx provides a mock function with given fields: tx
func (_m *MockSellDetailRepository) WithTx(tx *gorm.DB) repository.SellDetailRepository {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 repository.SellDetailRepository
	if rf, ok := ret.Get(0).(func(*gorm.DB) repository.SellDetailRepository); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.SellDetailRepository)
		}
	}

	return r0
}

// NewMockSellDetailRepository creates a new instance of MockSellDetailRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSellDetailRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSellDetailRepository {
	mock := &MockSellDetailRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
