// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/weeranieb/boonmafarm-backend/src/internal/model"
)

// MockWorkerRepository is an autogenerated mock type for the WorkerRepository type
type MockWorkerRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, worker
func (_m *MockWorkerRepository) Create(ctx context.Context, worker *model.Worker) error {
	ret := _m.Called(ctx, worker)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Worker) error); ok {
		r0 = rf(ctx, worker)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByFarmGroupId provides a mock function with given fields: farmGroupId
func (_m *MockWorkerRepository) GetByFarmGroupId(farmGroupId int) (*model.Worker, error) {
	ret := _m.Called(farmGroupId)

	if len(ret) == 0 {
		panic("no return value specified for GetByFarmGroupId")
	}

	var r0 *model.Worker
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*model.Worker, error)); ok {
		return rf(farmGroupId)
	}
	if rf, ok := ret.Get(0).(func(int) *model.Worker); ok {
		r0 = rf(farmGroupId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Worker)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(farmGroupId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *MockWorkerRepository) GetByID(id int) (*model.Worker, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Worker
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*model.Worker, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *model.Worker); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Worker)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPage provides a mock function with given fields: clientId, page, pageSize, orderBy, keyword
func (_m *MockWorkerRepository) GetPage(clientId int, page int, pageSize int, orderBy string, keyword string) ([]*model.Worker, int64, error) {
	ret := _m.Called(clientId, page, pageSize, orderBy, keyword)

	if len(ret) == 0 {
		panic("no return value specified for GetPage")
	}

	var r0 []*model.Worker
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int, int, string, string) ([]*model.Worker, int64, error)); ok {
		return rf(clientId, page, pageSize, orderBy, keyword)
	}
	if rf, ok := ret.Get(0).(func(int, int, int, string, string) []*model.Worker); ok {
		r0 = rf(clientId, page, pageSize, orderBy, keyword)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Worker)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, int, string, string) int64); ok {
		r1 = rf(clientId, page, pageSize, orderBy, keyword)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(int, int, int, string, string) error); ok {
		r2 = rf(clientId, page, pageSize, orderBy, keyword)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: ctx, worker
func (_m *MockWorkerRepository) Update(ctx context.Context, worker *model.Worker) error {
	ret := _m.Called(ctx, worker)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Worker) error); ok {
		r0 = rf(ctx, worker)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockWorkerRepository creates a new instance of MockWorkerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkerRepository {
	mock := &MockWorkerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
