// Code generated by mockery v2.53.5. DO NOT EDIT.

package service

import (
	mock "github.com/stretchr/testify/mock"
	dto "github.com/weeranieb/boonmafarm-backend/src/internal/dto"

	time "time"
)

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

// Login provides a mock function with given fields: request
func (_m *MockAuthService) Login(request dto.LoginRequest) (string, *dto.UserResponse, *time.Time, error) {
	ret := _m.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 *dto.UserResponse
	var r2 *time.Time
	var r3 error
	if rf, ok := ret.Get(0).(func(dto.LoginRequest) (string, *dto.UserResponse, *time.Time, error)); ok {
		return rf(request)
	}
	if rf, ok := ret.Get(0).(func(dto.LoginRequest) string); ok {
		r0 = rf(request)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(dto.LoginRequest) *dto.UserResponse); ok {
		r1 = rf(request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*dto.UserResponse)
		}
	}

	if rf, ok := ret.Get(2).(func(dto.LoginRequest) *time.Time); ok {
		r2 = rf(request)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(*time.Time)
		}
	}

	if rf, ok := ret.Get(3).(func(dto.LoginRequest) error); ok {
		r3 = rf(request)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// Register provides a mock function with given fields: request
func (_m *MockAuthService) Register(request dto.RegisterRequest) (*dto.UserResponse, error) {
	ret := _m.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *dto.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.RegisterRequest) (*dto.UserResponse, error)); ok {
		return rf(request)
	}
	if rf, ok := ret.Get(0).(func(dto.RegisterRequest) *dto.UserResponse); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(dto.RegisterRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
