// Code generated by mockery v2.53.5. DO NOT EDIT.

package service

import (
	mock "github.com/stretchr/testify/mock"
	dto "github.com/weeranieb/boonmafarm-backend/src/internal/dto"

	model "github.com/weeranieb/boonmafarm-backend/src/internal/model"
)

// MockClientService is an autogenerated mock type for the ClientService type
type MockClientService struct {
	mock.Mock
}

// Create provides a mock function with given fields: request, username
func (_m *MockClientService) Create(request dto.CreateClientRequest, username string) (*dto.ClientResponse, error) {
	ret := _m.Called(request, username)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *dto.ClientResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.CreateClientRequest, string) (*dto.ClientResponse, error)); ok {
		return rf(request, username)
	}
	if rf, ok := ret.Get(0).(func(dto.CreateClientRequest, string) *dto.ClientResponse); ok {
		r0 = rf(request, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ClientResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(dto.CreateClientRequest, string) error); ok {
		r1 = rf(request, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: id
func (_m *MockClientService) Get(id int) (*dto.ClientResponse, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *dto.ClientResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*dto.ClientResponse, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *dto.ClientResponse); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ClientResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetList provides a mock function with no fields
func (_m *MockClientService) GetList() ([]*dto.ClientResponse, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetList")
	}

	var r0 []*dto.ClientResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*dto.ClientResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*dto.ClientResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.ClientResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: request, username
func (_m *MockClientService) Update(request *model.Client, username string) error {
	ret := _m.Called(request, username)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Client, string) error); ok {
		r0 = rf(request, username)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockClientService creates a new instance of MockClientService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientService {
	mock := &MockClientService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
