// Code generated by mockery v2.53.6. DO NOT EDIT.

package service

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	dto "github.com/weeranieb/boonmafarm-backend/src/internal/dto"
)

// MockDailyLogService is an autogenerated mock type for the DailyLogService type
type MockDailyLogService struct {
	mock.Mock
}

// BulkUpsert provides a mock function with given fields: ctx, pondId, request, username
func (_m *MockDailyLogService) BulkUpsert(ctx context.Context, pondId int, request dto.DailyLogBulkUpsertRequest, username string) error {
	ret := _m.Called(ctx, pondId, request, username)

	if len(ret) == 0 {
		panic("no return value specified for BulkUpsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, dto.DailyLogBulkUpsertRequest, string) error); ok {
		r0 = rf(ctx, pondId, request, username)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMonth provides a mock function with given fields: ctx, pondId, month
func (_m *MockDailyLogService) GetMonth(ctx context.Context, pondId int, month string) (*dto.DailyLogMonthResponse, error) {
	ret := _m.Called(ctx, pondId, month)

	if len(ret) == 0 {
		panic("no return value specified for GetMonth")
	}

	var r0 *dto.DailyLogMonthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string) (*dto.DailyLogMonthResponse, error)); ok {
		return rf(ctx, pondId, month)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, string) *dto.DailyLogMonthResponse); ok {
		r0 = rf(ctx, pondId, month)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.DailyLogMonthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, string) error); ok {
		r1 = rf(ctx, pondId, month)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ImportFromTemplate provides a mock function with given fields: ctx, farmId, selectedPondIds, file, username
func (_m *MockDailyLogService) ImportFromTemplate(ctx context.Context, farmId int, selectedPondIds []int, file []byte, username string) (*dto.DailyLogTemplateImportResponse, error) {
	ret := _m.Called(ctx, farmId, selectedPondIds, file, username)

	if len(ret) == 0 {
		panic("no return value specified for ImportFromTemplate")
	}

	var r0 *dto.DailyLogTemplateImportResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, []int, []byte, string) (*dto.DailyLogTemplateImportResponse, error)); ok {
		return rf(ctx, farmId, selectedPondIds, file, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, []int, []byte, string) *dto.DailyLogTemplateImportResponse); ok {
		r0 = rf(ctx, farmId, selectedPondIds, file, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.DailyLogTemplateImportResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, []int, []byte, string) error); ok {
		r1 = rf(ctx, farmId, selectedPondIds, file, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockDailyLogService creates a new instance of MockDailyLogService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDailyLogService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDailyLogService {
	mock := &MockDailyLogService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
