// Code generated by mockery v2.53.5. DO NOT EDIT.

package service

import (
	mock "github.com/stretchr/testify/mock"
	dto "github.com/weeranieb/boonmafarm-backend/src/internal/dto"

	model "github.com/weeranieb/boonmafarm-backend/src/internal/model"
)

// MockFarmService is an autogenerated mock type for the FarmService type
type MockFarmService struct {
	mock.Mock
}

// Create provides a mock function with given fields: request, username, clientId
func (_m *MockFarmService) Create(request dto.CreateFarmRequest, username string, clientId int) (*dto.FarmResponse, error) {
	ret := _m.Called(request, username, clientId)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *dto.FarmResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.CreateFarmRequest, string, int) (*dto.FarmResponse, error)); ok {
		return rf(request, username, clientId)
	}
	if rf, ok := ret.Get(0).(func(dto.CreateFarmRequest, string, int) *dto.FarmResponse); ok {
		r0 = rf(request, username, clientId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.FarmResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(dto.CreateFarmRequest, string, int) error); ok {
		r1 = rf(request, username, clientId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: id, clientId
func (_m *MockFarmService) Get(id int, clientId int) (*dto.FarmResponse, error) {
	ret := _m.Called(id, clientId)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *dto.FarmResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) (*dto.FarmResponse, error)); ok {
		return rf(id, clientId)
	}
	if rf, ok := ret.Get(0).(func(int, int) *dto.FarmResponse); ok {
		r0 = rf(id, clientId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.FarmResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(id, clientId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFarmIdByName provides a mock function with given fields: farmName, clientId
func (_m *MockFarmService) GetFarmIdByName(farmName string, clientId int) (int, error) {
	ret := _m.Called(farmName, clientId)

	if len(ret) == 0 {
		panic("no return value specified for GetFarmIdByName")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) (int, error)); ok {
		return rf(farmName, clientId)
	}
	if rf, ok := ret.Get(0).(func(string, int) int); ok {
		r0 = rf(farmName, clientId)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(farmName, clientId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetList provides a mock function with given fields: clientId
func (_m *MockFarmService) GetList(clientId int) ([]*dto.FarmResponse, error) {
	ret := _m.Called(clientId)

	if len(ret) == 0 {
		panic("no return value specified for GetList")
	}

	var r0 []*dto.FarmResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]*dto.FarmResponse, error)); ok {
		return rf(clientId)
	}
	if rf, ok := ret.Get(0).(func(int) []*dto.FarmResponse); ok {
		r0 = rf(clientId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.FarmResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(clientId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: request, username
func (_m *MockFarmService) Update(request *model.Farm, username string) error {
	ret := _m.Called(request, username)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Farm, string) error); ok {
		r0 = rf(request, username)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockFarmService creates a new instance of MockFarmService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFarmService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFarmService {
	mock := &MockFarmService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
