// Code generated by mockery v2.53.6. DO NOT EDIT.

package service

import (
	context "context"

	decimal "github.com/shopspring/decimal"
	mock "github.com/stretchr/testify/mock"

	model "github.com/weeranieb/boonmafarm-backend/src/internal/model"
)

// MockFeedCostCalculator is an autogenerated mock type for the FeedCostCalculator type
type MockFeedCostCalculator struct {
	mock.Mock
}

// CalcCycleFeedCost provides a mock function with given fields: ctx, activePond
func (_m *MockFeedCostCalculator) CalcCycleFeedCost(ctx context.Context, activePond *model.ActivePond) (decimal.Decimal, error) {
	ret := _m.Called(ctx, activePond)

	if len(ret) == 0 {
		panic("no return value specified for CalcCycleFeedCost")
	}

	var r0 decimal.Decimal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.ActivePond) (decimal.Decimal, error)); ok {
		return rf(ctx, activePond)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.ActivePond) decimal.Decimal); ok {
		r0 = rf(ctx, activePond)
	} else {
		r0 = ret.Get(0).(decimal.Decimal)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.ActivePond) error); ok {
		r1 = rf(ctx, activePond)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CalcCycleFeedCostBatch provides a mock function with given fields: ctx, activePonds
func (_m *MockFeedCostCalculator) CalcCycleFeedCostBatch(ctx context.Context, activePonds []*model.ActivePond) (map[int]decimal.Decimal, error) {
	ret := _m.Called(ctx, activePonds)

	if len(ret) == 0 {
		panic("no return value specified for CalcCycleFeedCostBatch")
	}

	var r0 map[int]decimal.Decimal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []*model.ActivePond) (map[int]decimal.Decimal, error)); ok {
		return rf(ctx, activePonds)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []*model.ActivePond) map[int]decimal.Decimal); ok {
		r0 = rf(ctx, activePonds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int]decimal.Decimal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []*model.ActivePond) error); ok {
		r1 = rf(ctx, activePonds)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockFeedCostCalculator creates a new instance of MockFeedCostCalculator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFeedCostCalculator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFeedCostCalculator {
	mock := &MockFeedCostCalculator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
