// Code generated by mockery v2.53.6. DO NOT EDIT.

package service

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	dto "github.com/weeranieb/boonmafarm-backend/src/internal/dto"
)

// MockFeedCollectionService is an autogenerated mock type for the FeedCollectionService type
type MockFeedCollectionService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, request, username, clientId
func (_m *MockFeedCollectionService) Create(ctx context.Context, request dto.CreateFeedCollectionRequest, username string, clientId int) (*dto.CreateFeedCollectionResponse, error) {
	ret := _m.Called(ctx, request, username, clientId)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *dto.CreateFeedCollectionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateFeedCollectionRequest, string, int) (*dto.CreateFeedCollectionResponse, error)); ok {
		return rf(ctx, request, username, clientId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateFeedCollectionRequest, string, int) *dto.CreateFeedCollectionResponse); ok {
		r0 = rf(ctx, request, username, clientId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.CreateFeedCollectionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateFeedCollectionRequest, string, int) error); ok {
		r1 = rf(ctx, request, username, clientId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: id
func (_m *MockFeedCollectionService) Get(id int) (*dto.FeedCollectionResponse, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *dto.FeedCollectionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*dto.FeedCollectionResponse, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *dto.FeedCollectionResponse); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.FeedCollectionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPage provides a mock function with given fields: clientId, page, pageSize, orderBy, keyword
func (_m *MockFeedCollectionService) GetPage(clientId int, page int, pageSize int, orderBy string, keyword string) (*dto.PageResponse, error) {
	ret := _m.Called(clientId, page, pageSize, orderBy, keyword)

	if len(ret) == 0 {
		panic("no return value specified for GetPage")
	}

	var r0 *dto.PageResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, int, string, string) (*dto.PageResponse, error)); ok {
		return rf(clientId, page, pageSize, orderBy, keyword)
	}
	if rf, ok := ret.Get(0).(func(int, int, int, string, string) *dto.PageResponse); ok {
		r0 = rf(clientId, page, pageSize, orderBy, keyword)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PageResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, int, string, string) error); ok {
		r1 = rf(clientId, page, pageSize, orderBy, keyword)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, request, username
func (_m *MockFeedCollectionService) Update(ctx context.Context, request dto.UpdateFeedCollectionRequest, username string) error {
	ret := _m.Called(ctx, request, username)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.UpdateFeedCollectionRequest, string) error); ok {
		r0 = rf(ctx, request, username)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockFeedCollectionService creates a new instance of MockFeedCollectionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFeedCollectionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFeedCollectionService {
	mock := &MockFeedCollectionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
