// Code generated by mockery v2.53.5. DO NOT EDIT.

package service

import (
	mock "github.com/stretchr/testify/mock"
	dto "github.com/weeranieb/boonmafarm-backend/src/internal/dto"

	model "github.com/weeranieb/boonmafarm-backend/src/internal/model"
)

// MockFeedPriceHistoryService is an autogenerated mock type for the FeedPriceHistoryService type
type MockFeedPriceHistoryService struct {
	mock.Mock
}

// Create provides a mock function with given fields: request, username
func (_m *MockFeedPriceHistoryService) Create(request dto.CreateFeedPriceHistoryRequest, username string) (*dto.FeedPriceHistoryResponse, error) {
	ret := _m.Called(request, username)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *dto.FeedPriceHistoryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.CreateFeedPriceHistoryRequest, string) (*dto.FeedPriceHistoryResponse, error)); ok {
		return rf(request, username)
	}
	if rf, ok := ret.Get(0).(func(dto.CreateFeedPriceHistoryRequest, string) *dto.FeedPriceHistoryResponse); ok {
		r0 = rf(request, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.FeedPriceHistoryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(dto.CreateFeedPriceHistoryRequest, string) error); ok {
		r1 = rf(request, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: id
func (_m *MockFeedPriceHistoryService) Get(id int) (*dto.FeedPriceHistoryResponse, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *dto.FeedPriceHistoryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*dto.FeedPriceHistoryResponse, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *dto.FeedPriceHistoryResponse); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.FeedPriceHistoryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: feedCollectionId
func (_m *MockFeedPriceHistoryService) GetAll(feedCollectionId int) ([]*dto.FeedPriceHistoryResponse, error) {
	ret := _m.Called(feedCollectionId)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*dto.FeedPriceHistoryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]*dto.FeedPriceHistoryResponse, error)); ok {
		return rf(feedCollectionId)
	}
	if rf, ok := ret.Get(0).(func(int) []*dto.FeedPriceHistoryResponse); ok {
		r0 = rf(feedCollectionId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.FeedPriceHistoryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(feedCollectionId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: request, username
func (_m *MockFeedPriceHistoryService) Update(request *model.FeedPriceHistory, username string) error {
	ret := _m.Called(request, username)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.FeedPriceHistory, string) error); ok {
		r0 = rf(request, username)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockFeedPriceHistoryService creates a new instance of MockFeedPriceHistoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFeedPriceHistoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFeedPriceHistoryService {
	mock := &MockFeedPriceHistoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
