// Code generated by mockery v2.53.6. DO NOT EDIT.

package service

import (
	mock "github.com/stretchr/testify/mock"
	dto "github.com/weeranieb/boonmafarm-backend/src/internal/dto"
)

// MockFishSizeGradeService is an autogenerated mock type for the FishSizeGradeService type
type MockFishSizeGradeService struct {
	mock.Mock
}

// GetDropdown provides a mock function with no fields
func (_m *MockFishSizeGradeService) GetDropdown() ([]*dto.DropdownItem, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDropdown")
	}

	var r0 []*dto.DropdownItem
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*dto.DropdownItem, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*dto.DropdownItem); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.DropdownItem)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockFishSizeGradeService creates a new instance of MockFishSizeGradeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFishSizeGradeService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFishSizeGradeService {
	mock := &MockFishSizeGradeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
