// Code generated by mockery v2.53.5. DO NOT EDIT.

package service

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	dto "github.com/weeranieb/boonmafarm-backend/src/internal/dto"

	model "github.com/weeranieb/boonmafarm-backend/src/internal/model"
)

// MockMerchantService is an autogenerated mock type for the MerchantService type
type MockMerchantService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, request, username
func (_m *MockMerchantService) Create(ctx context.Context, request dto.CreateMerchantRequest, username string) (*dto.MerchantResponse, error) {
	ret := _m.Called(ctx, request, username)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *dto.MerchantResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateMerchantRequest, string) (*dto.MerchantResponse, error)); ok {
		return rf(ctx, request, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateMerchantRequest, string) *dto.MerchantResponse); ok {
		r0 = rf(ctx, request, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.MerchantResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateMerchantRequest, string) error); ok {
		r1 = rf(ctx, request, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: id
func (_m *MockMerchantService) Get(id int) (*dto.MerchantResponse, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *dto.MerchantResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*dto.MerchantResponse, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *dto.MerchantResponse); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.MerchantResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetList provides a mock function with no fields
func (_m *MockMerchantService) GetList() ([]*dto.MerchantResponse, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetList")
	}

	var r0 []*dto.MerchantResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*dto.MerchantResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*dto.MerchantResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.MerchantResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, request, username
func (_m *MockMerchantService) Update(ctx context.Context, request *model.Merchant, username string) error {
	ret := _m.Called(ctx, request, username)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Merchant, string) error); ok {
		r0 = rf(ctx, request, username)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockMerchantService creates a new instance of MockMerchantService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMerchantService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMerchantService {
	mock := &MockMerchantService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
