// Code generated by mockery v2.53.6. DO NOT EDIT.

package service

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	dto "github.com/weeranieb/boonmafarm-backend/src/internal/dto"
)

// MockPondService is an autogenerated mock type for the PondService type
type MockPondService struct {
	mock.Mock
}

// CreatePonds provides a mock function with given fields: ctx, request
func (_m *MockPondService) CreatePonds(ctx context.Context, request dto.CreatePondsRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreatePonds")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreatePondsRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockPondService) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FillPond provides a mock function with given fields: ctx, pondId, request, username
func (_m *MockPondService) FillPond(ctx context.Context, pondId int, request dto.PondFillRequest, username string) (*dto.PondFillResponse, error) {
	ret := _m.Called(ctx, pondId, request, username)

	if len(ret) == 0 {
		panic("no return value specified for FillPond")
	}

	var r0 *dto.PondFillResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, dto.PondFillRequest, string) (*dto.PondFillResponse, error)); ok {
		return rf(ctx, pondId, request, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, dto.PondFillRequest, string) *dto.PondFillResponse); ok {
		r0 = rf(ctx, pondId, request, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PondFillResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, dto.PondFillRequest, string) error); ok {
		r1 = rf(ctx, pondId, request, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockPondService) Get(ctx context.Context, id int) (*dto.PondResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *dto.PondResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*dto.PondResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *dto.PondResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PondResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetList provides a mock function with given fields: ctx, farmId
func (_m *MockPondService) GetList(ctx context.Context, farmId int) ([]*dto.PondResponse, error) {
	ret := _m.Called(ctx, farmId)

	if len(ret) == 0 {
		panic("no return value specified for GetList")
	}

	var r0 []*dto.PondResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*dto.PondResponse, error)); ok {
		return rf(ctx, farmId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*dto.PondResponse); ok {
		r0 = rf(ctx, farmId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.PondResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, farmId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MovePond provides a mock function with given fields: ctx, sourcePondId, request, username
func (_m *MockPondService) MovePond(ctx context.Context, sourcePondId int, request dto.PondMoveRequest, username string) (*dto.PondMoveResponse, error) {
	ret := _m.Called(ctx, sourcePondId, request, username)

	if len(ret) == 0 {
		panic("no return value specified for MovePond")
	}

	var r0 *dto.PondMoveResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, dto.PondMoveRequest, string) (*dto.PondMoveResponse, error)); ok {
		return rf(ctx, sourcePondId, request, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, dto.PondMoveRequest, string) *dto.PondMoveResponse); ok {
		r0 = rf(ctx, sourcePondId, request, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PondMoveResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, dto.PondMoveRequest, string) error); ok {
		r1 = rf(ctx, sourcePondId, request, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PreviewFillPond provides a mock function with given fields: ctx, pondId, request
func (_m *MockPondService) PreviewFillPond(ctx context.Context, pondId int, request dto.PondFillRequest) (*dto.PondFillPreviewResponse, error) {
	ret := _m.Called(ctx, pondId, request)

	if len(ret) == 0 {
		panic("no return value specified for PreviewFillPond")
	}

	var r0 *dto.PondFillPreviewResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, dto.PondFillRequest) (*dto.PondFillPreviewResponse, error)); ok {
		return rf(ctx, pondId, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, dto.PondFillRequest) *dto.PondFillPreviewResponse); ok {
		r0 = rf(ctx, pondId, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PondFillPreviewResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, dto.PondFillRequest) error); ok {
		r1 = rf(ctx, pondId, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PreviewMovePond provides a mock function with given fields: ctx, sourcePondId, request
func (_m *MockPondService) PreviewMovePond(ctx context.Context, sourcePondId int, request dto.PondMoveRequest) (*dto.PondMovePreviewResponse, error) {
	ret := _m.Called(ctx, sourcePondId, request)

	if len(ret) == 0 {
		panic("no return value specified for PreviewMovePond")
	}

	var r0 *dto.PondMovePreviewResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, dto.PondMoveRequest) (*dto.PondMovePreviewResponse, error)); ok {
		return rf(ctx, sourcePondId, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, dto.PondMoveRequest) *dto.PondMovePreviewResponse); ok {
		r0 = rf(ctx, sourcePondId, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PondMovePreviewResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, dto.PondMoveRequest) error); ok {
		r1 = rf(ctx, sourcePondId, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PreviewSellPond provides a mock function with given fields: ctx, pondId, request
func (_m *MockPondService) PreviewSellPond(ctx context.Context, pondId int, request dto.PondSellRequest) (*dto.PondSellPreviewResponse, error) {
	ret := _m.Called(ctx, pondId, request)

	if len(ret) == 0 {
		panic("no return value specified for PreviewSellPond")
	}

	var r0 *dto.PondSellPreviewResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, dto.PondSellRequest) (*dto.PondSellPreviewResponse, error)); ok {
		return rf(ctx, pondId, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, dto.PondSellRequest) *dto.PondSellPreviewResponse); ok {
		r0 = rf(ctx, pondId, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PondSellPreviewResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, dto.PondSellRequest) error); ok {
		r1 = rf(ctx, pondId, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SellPond provides a mock function with given fields: ctx, pondId, request, username
func (_m *MockPondService) SellPond(ctx context.Context, pondId int, request dto.PondSellRequest, username string) (*dto.PondSellResponse, error) {
	ret := _m.Called(ctx, pondId, request, username)

	if len(ret) == 0 {
		panic("no return value specified for SellPond")
	}

	var r0 *dto.PondSellResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, dto.PondSellRequest, string) (*dto.PondSellResponse, error)); ok {
		return rf(ctx, pondId, request, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, dto.PondSellRequest, string) *dto.PondSellResponse); ok {
		r0 = rf(ctx, pondId, request, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PondSellResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, dto.PondSellRequest, string) error); ok {
		r1 = rf(ctx, pondId, request, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, request
func (_m *MockPondService) Update(ctx context.Context, request dto.UpdatePondRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.UpdatePondRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockPondService creates a new instance of MockPondService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPondService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPondService {
	mock := &MockPondService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
