// Code generated by mockery v2.53.5. DO NOT EDIT.

package service

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	dto "github.com/weeranieb/boonmafarm-backend/src/internal/dto"
)

// MockPondService is an autogenerated mock type for the PondService type
type MockPondService struct {
	mock.Mock
}

// CreatePonds provides a mock function with given fields: ctx, request, username
func (_m *MockPondService) CreatePonds(ctx context.Context, request dto.CreatePondsRequest, username string) error {
	ret := _m.Called(ctx, request, username)

	if len(ret) == 0 {
		panic("no return value specified for CreatePonds")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreatePondsRequest, string) error); ok {
		r0 = rf(ctx, request, username)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id, username
func (_m *MockPondService) Delete(id int, username string) error {
	ret := _m.Called(id, username)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, string) error); ok {
		r0 = rf(id, username)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FillPond provides a mock function with given fields: ctx, pondId, request, username
func (_m *MockPondService) FillPond(ctx context.Context, pondId int, request dto.PondFillRequest, username string) (*dto.PondFillResponse, error) {
	ret := _m.Called(ctx, pondId, request, username)

	if len(ret) == 0 {
		panic("no return value specified for FillPond")
	}

	var r0 *dto.PondFillResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, dto.PondFillRequest, string) (*dto.PondFillResponse, error)); ok {
		return rf(ctx, pondId, request, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, dto.PondFillRequest, string) *dto.PondFillResponse); ok {
		r0 = rf(ctx, pondId, request, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PondFillResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, dto.PondFillRequest, string) error); ok {
		r1 = rf(ctx, pondId, request, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: id
func (_m *MockPondService) Get(id int) (*dto.PondResponse, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *dto.PondResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*dto.PondResponse, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *dto.PondResponse); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PondResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetList provides a mock function with given fields: farmId
func (_m *MockPondService) GetList(farmId int) ([]*dto.PondResponse, error) {
	ret := _m.Called(farmId)

	if len(ret) == 0 {
		panic("no return value specified for GetList")
	}

	var r0 []*dto.PondResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]*dto.PondResponse, error)); ok {
		return rf(farmId)
	}
	if rf, ok := ret.Get(0).(func(int) []*dto.PondResponse); ok {
		r0 = rf(farmId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.PondResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(farmId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, request, username
func (_m *MockPondService) Update(ctx context.Context, request dto.UpdatePondRequest, username string) error {
	ret := _m.Called(ctx, request, username)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.UpdatePondRequest, string) error); ok {
		r0 = rf(ctx, request, username)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockPondService creates a new instance of MockPondService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPondService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPondService {
	mock := &MockPondService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
