// Code generated by mockery v2.53.5. DO NOT EDIT.

package service

import (
	mock "github.com/stretchr/testify/mock"
	dto "github.com/weeranieb/boonmafarm-backend/src/internal/dto"

	model "github.com/weeranieb/boonmafarm-backend/src/internal/model"
)

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

// Create provides a mock function with given fields: request, userIdentity, clientId
func (_m *MockUserService) Create(request dto.CreateUserRequest, userIdentity string, clientId int) (*dto.UserResponse, error) {
	ret := _m.Called(request, userIdentity, clientId)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *dto.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.CreateUserRequest, string, int) (*dto.UserResponse, error)); ok {
		return rf(request, userIdentity, clientId)
	}
	if rf, ok := ret.Get(0).(func(dto.CreateUserRequest, string, int) *dto.UserResponse); ok {
		r0 = rf(request, userIdentity, clientId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(dto.CreateUserRequest, string, int) error); ok {
		r1 = rf(request, userIdentity, clientId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUser provides a mock function with given fields: id
func (_m *MockUserService) GetUser(id int) (*dto.UserResponse, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *dto.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*dto.UserResponse, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *dto.UserResponse); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserList provides a mock function with given fields: clientId
func (_m *MockUserService) GetUserList(clientId int) ([]*dto.UserResponse, error) {
	ret := _m.Called(clientId)

	if len(ret) == 0 {
		panic("no return value specified for GetUserList")
	}

	var r0 []*dto.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]*dto.UserResponse, error)); ok {
		return rf(clientId)
	}
	if rf, ok := ret.Get(0).(func(int) []*dto.UserResponse); ok {
		r0 = rf(clientId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(clientId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: request, userIdentity
func (_m *MockUserService) Update(request *model.User, userIdentity string) error {
	ret := _m.Called(request, userIdentity)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.User, string) error); ok {
		r0 = rf(request, userIdentity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
