// Code generated by mockery v2.53.5. DO NOT EDIT.

package service

import (
	mock "github.com/stretchr/testify/mock"
	dto "github.com/weeranieb/boonmafarm-backend/src/internal/dto"

	model "github.com/weeranieb/boonmafarm-backend/src/internal/model"
)

// MockWorkerService is an autogenerated mock type for the WorkerService type
type MockWorkerService struct {
	mock.Mock
}

// Create provides a mock function with given fields: request, username, clientId
func (_m *MockWorkerService) Create(request dto.CreateWorkerRequest, username string, clientId int) (*dto.WorkerResponse, error) {
	ret := _m.Called(request, username, clientId)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *dto.WorkerResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.CreateWorkerRequest, string, int) (*dto.WorkerResponse, error)); ok {
		return rf(request, username, clientId)
	}
	if rf, ok := ret.Get(0).(func(dto.CreateWorkerRequest, string, int) *dto.WorkerResponse); ok {
		r0 = rf(request, username, clientId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.WorkerResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(dto.CreateWorkerRequest, string, int) error); ok {
		r1 = rf(request, username, clientId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: id
func (_m *MockWorkerService) Get(id int) (*dto.WorkerResponse, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *dto.WorkerResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*dto.WorkerResponse, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *dto.WorkerResponse); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.WorkerResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPage provides a mock function with given fields: clientId, page, pageSize, orderBy, keyword
func (_m *MockWorkerService) GetPage(clientId int, page int, pageSize int, orderBy string, keyword string) (*dto.PageResponse, error) {
	ret := _m.Called(clientId, page, pageSize, orderBy, keyword)

	if len(ret) == 0 {
		panic("no return value specified for GetPage")
	}

	var r0 *dto.PageResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, int, string, string) (*dto.PageResponse, error)); ok {
		return rf(clientId, page, pageSize, orderBy, keyword)
	}
	if rf, ok := ret.Get(0).(func(int, int, int, string, string) *dto.PageResponse); ok {
		r0 = rf(clientId, page, pageSize, orderBy, keyword)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PageResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, int, string, string) error); ok {
		r1 = rf(clientId, page, pageSize, orderBy, keyword)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: request, username
func (_m *MockWorkerService) Update(request *model.Worker, username string) error {
	ret := _m.Called(request, username)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Worker, string) error); ok {
		r0 = rf(request, username)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockWorkerService creates a new instance of MockWorkerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkerService {
	mock := &MockWorkerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
