// Code generated by mockery v2.53.6. DO NOT EDIT.

package handler

import (
	fiber "github.com/gofiber/fiber/v2"

	mock "github.com/stretchr/testify/mock"
)

// MockDailyLogHandler is an autogenerated mock type for the DailyLogHandler type
type MockDailyLogHandler struct {
	mock.Mock
}

// BulkUpsert provides a mock function with given fields: c
func (_m *MockDailyLogHandler) BulkUpsert(c *fiber.Ctx) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for BulkUpsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMonth provides a mock function with given fields: c
func (_m *MockDailyLogHandler) GetMonth(c *fiber.Ctx) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GetMonth")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UploadTemplate provides a mock function with given fields: c
func (_m *MockDailyLogHandler) UploadTemplate(c *fiber.Ctx) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for UploadTemplate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockDailyLogHandler creates a new instance of MockDailyLogHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDailyLogHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDailyLogHandler {
	mock := &MockDailyLogHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
