// Code generated by mockery v2.53.5. DO NOT EDIT.

package handler

import (
	fiber "github.com/gofiber/fiber/v2"

	mock "github.com/stretchr/testify/mock"
)

// MockFeedCollectionHandler is an autogenerated mock type for the FeedCollectionHandler type
type MockFeedCollectionHandler struct {
	mock.Mock
}

// AddFeedCollection provides a mock function with given fields: c
func (_m *MockFeedCollectionHandler) AddFeedCollection(c *fiber.Ctx) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for AddFeedCollection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetFeedCollection provides a mock function with given fields: c
func (_m *MockFeedCollectionHandler) GetFeedCollection(c *fiber.Ctx) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GetFeedCollection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListFeedCollection provides a mock function with given fields: c
func (_m *MockFeedCollectionHandler) ListFeedCollection(c *fiber.Ctx) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for ListFeedCollection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateFeedCollection provides a mock function with given fields: c
func (_m *MockFeedCollectionHandler) UpdateFeedCollection(c *fiber.Ctx) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFeedCollection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockFeedCollectionHandler creates a new instance of MockFeedCollectionHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFeedCollectionHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFeedCollectionHandler {
	mock := &MockFeedCollectionHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
