// Code generated by mockery v2.53.6. DO NOT EDIT.

package handler

import (
	fiber "github.com/gofiber/fiber/v2"

	mock "github.com/stretchr/testify/mock"
)

// MockFeedPriceHistoryHandler is an autogenerated mock type for the FeedPriceHistoryHandler type
type MockFeedPriceHistoryHandler struct {
	mock.Mock
}

// AddFeedPriceHistory provides a mock function with given fields: c
func (_m *MockFeedPriceHistoryHandler) AddFeedPriceHistory(c *fiber.Ctx) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for AddFeedPriceHistory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllFeedPriceHistory provides a mock function with given fields: c
func (_m *MockFeedPriceHistoryHandler) GetAllFeedPriceHistory(c *fiber.Ctx) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GetAllFeedPriceHistory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetFeedPriceHistory provides a mock function with given fields: c
func (_m *MockFeedPriceHistoryHandler) GetFeedPriceHistory(c *fiber.Ctx) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GetFeedPriceHistory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateFeedPriceHistory provides a mock function with given fields: c
func (_m *MockFeedPriceHistoryHandler) UpdateFeedPriceHistory(c *fiber.Ctx) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFeedPriceHistory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockFeedPriceHistoryHandler creates a new instance of MockFeedPriceHistoryHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFeedPriceHistoryHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFeedPriceHistoryHandler {
	mock := &MockFeedPriceHistoryHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
