// Code generated by mockery v2.53.6. DO NOT EDIT.

package handler

import (
	fiber "github.com/gofiber/fiber/v2"

	mock "github.com/stretchr/testify/mock"
)

// MockFishSizeGradeHandler is an autogenerated mock type for the FishSizeGradeHandler type
type MockFishSizeGradeHandler struct {
	mock.Mock
}

// GetDropdown provides a mock function with given fields: c
func (_m *MockFishSizeGradeHandler) GetDropdown(c *fiber.Ctx) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GetDropdown")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockFishSizeGradeHandler creates a new instance of MockFishSizeGradeHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFishSizeGradeHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFishSizeGradeHandler {
	mock := &MockFishSizeGradeHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
