// Code generated by mockery v2.53.5. DO NOT EDIT.

package handler

import (
	fiber "github.com/gofiber/fiber/v2"

	mock "github.com/stretchr/testify/mock"
)

// MockMerchantHandler is an autogenerated mock type for the MerchantHandler type
type MockMerchantHandler struct {
	mock.Mock
}

// AddMerchant provides a mock function with given fields: c
func (_m *MockMerchantHandler) AddMerchant(c *fiber.Ctx) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for AddMerchant")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMerchant provides a mock function with given fields: c
func (_m *MockMerchantHandler) GetMerchant(c *fiber.Ctx) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GetMerchant")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMerchantList provides a mock function with given fields: c
func (_m *MockMerchantHandler) GetMerchantList(c *fiber.Ctx) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GetMerchantList")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateMerchant provides a mock function with given fields: c
func (_m *MockMerchantHandler) UpdateMerchant(c *fiber.Ctx) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMerchant")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockMerchantHandler creates a new instance of MockMerchantHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMerchantHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMerchantHandler {
	mock := &MockMerchantHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
