// Code generated by mockery v2.53.5. DO NOT EDIT.

package handler

import (
	fiber "github.com/gofiber/fiber/v2"

	mock "github.com/stretchr/testify/mock"
)

// MockWorkerHandler is an autogenerated mock type for the WorkerHandler type
type MockWorkerHandler struct {
	mock.Mock
}

// AddWorker provides a mock function with given fields: c
func (_m *MockWorkerHandler) AddWorker(c *fiber.Ctx) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for AddWorker")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetWorker provides a mock function with given fields: c
func (_m *MockWorkerHandler) GetWorker(c *fiber.Ctx) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GetWorker")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListWorker provides a mock function with given fields: c
func (_m *MockWorkerHandler) ListWorker(c *fiber.Ctx) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for ListWorker")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateWorker provides a mock function with given fields: c
func (_m *MockWorkerHandler) UpdateWorker(c *fiber.Ctx) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWorker")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockWorkerHandler creates a new instance of MockWorkerHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkerHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkerHandler {
	mock := &MockWorkerHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
