// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	models "boonmafarm/api/pkg/models"

	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"

	repositories "boonmafarm/api/pkg/repositories"
)

// IClientRepository is an autogenerated mock type for the IClientRepository type
type IClientRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: request
func (_m *IClientRepository) Create(request *models.Client) (*models.Client, error) {
	ret := _m.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.Client) (*models.Client, error)); ok {
		return rf(request)
	}
	if rf, ok := ret.Get(0).(func(*models.Client) *models.Client); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(*models.Client) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FirstByQuery provides a mock function with given fields: query, args
func (_m *IClientRepository) FirstByQuery(query interface{}, args ...interface{}) (*models.Client, error) {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for FirstByQuery")
	}

	var r0 *models.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}, ...interface{}) (*models.Client, error)); ok {
		return rf(query, args...)
	}
	if rf, ok := ret.Get(0).(func(interface{}, ...interface{}) *models.Client); ok {
		r0 = rf(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}, ...interface{}) error); ok {
		r1 = rf(query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TakeById provides a mock function with given fields: id
func (_m *IClientRepository) TakeById(id int) (*models.Client, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for TakeById")
	}

	var r0 *models.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*models.Client, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *models.Client); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WithTrx provides a mock function with given fields: trxHandle
func (_m *IClientRepository) WithTrx(trxHandle *gorm.DB) repositories.IClientRepository {
	ret := _m.Called(trxHandle)

	if len(ret) == 0 {
		panic("no return value specified for WithTrx")
	}

	var r0 repositories.IClientRepository
	if rf, ok := ret.Get(0).(func(*gorm.DB) repositories.IClientRepository); ok {
		r0 = rf(trxHandle)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repositories.IClientRepository)
		}
	}

	return r0
}

// NewIClientRepository creates a new instance of IClientRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIClientRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IClientRepository {
	mock := &IClientRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
