// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	models "boonmafarm/api/pkg/models"

	mock "github.com/stretchr/testify/mock"
)

// IFarmOnFarmGroupRepository is an autogenerated mock type for the IFarmOnFarmGroupRepository type
type IFarmOnFarmGroupRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: request
func (_m *IFarmOnFarmGroupRepository) Create(request *models.FarmOnFarmGroup) (*models.FarmOnFarmGroup, error) {
	ret := _m.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.FarmOnFarmGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.FarmOnFarmGroup) (*models.FarmOnFarmGroup, error)); ok {
		return rf(request)
	}
	if rf, ok := ret.Get(0).(func(*models.FarmOnFarmGroup) *models.FarmOnFarmGroup); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.FarmOnFarmGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(*models.FarmOnFarmGroup) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *IFarmOnFarmGroupRepository) Delete(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FirstByQuery provides a mock function with given fields: query, args
func (_m *IFarmOnFarmGroupRepository) FirstByQuery(query interface{}, args ...interface{}) (*models.FarmOnFarmGroup, error) {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for FirstByQuery")
	}

	var r0 *models.FarmOnFarmGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}, ...interface{}) (*models.FarmOnFarmGroup, error)); ok {
		return rf(query, args...)
	}
	if rf, ok := ret.Get(0).(func(interface{}, ...interface{}) *models.FarmOnFarmGroup); ok {
		r0 = rf(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.FarmOnFarmGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}, ...interface{}) error); ok {
		r1 = rf(query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIFarmOnFarmGroupRepository creates a new instance of IFarmOnFarmGroupRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIFarmOnFarmGroupRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IFarmOnFarmGroupRepository {
	mock := &IFarmOnFarmGroupRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
