// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	models "boonmafarm/api/pkg/models"

	mock "github.com/stretchr/testify/mock"
)

// IFarmRepository is an autogenerated mock type for the IFarmRepository type
type IFarmRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: request
func (_m *IFarmRepository) Create(request *models.Farm) (*models.Farm, error) {
	ret := _m.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Farm
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.Farm) (*models.Farm, error)); ok {
		return rf(request)
	}
	if rf, ok := ret.Get(0).(func(*models.Farm) *models.Farm); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Farm)
		}
	}

	if rf, ok := ret.Get(1).(func(*models.Farm) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FirstByQuery provides a mock function with given fields: query, args
func (_m *IFarmRepository) FirstByQuery(query interface{}, args ...interface{}) (*models.Farm, error) {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for FirstByQuery")
	}

	var r0 *models.Farm
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}, ...interface{}) (*models.Farm, error)); ok {
		return rf(query, args...)
	}
	if rf, ok := ret.Get(0).(func(interface{}, ...interface{}) *models.Farm); ok {
		r0 = rf(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Farm)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}, ...interface{}) error); ok {
		r1 = rf(query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TakeAll provides a mock function with given fields: clientId
func (_m *IFarmRepository) TakeAll(clientId int) ([]*models.Farm, error) {
	ret := _m.Called(clientId)

	if len(ret) == 0 {
		panic("no return value specified for TakeAll")
	}

	var r0 []*models.Farm
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]*models.Farm, error)); ok {
		return rf(clientId)
	}
	if rf, ok := ret.Get(0).(func(int) []*models.Farm); ok {
		r0 = rf(clientId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Farm)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(clientId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TakeById provides a mock function with given fields: id
func (_m *IFarmRepository) TakeById(id int) (*models.Farm, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for TakeById")
	}

	var r0 *models.Farm
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*models.Farm, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *models.Farm); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Farm)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: request
func (_m *IFarmRepository) Update(request *models.Farm) error {
	ret := _m.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Farm) error); ok {
		r0 = rf(request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIFarmRepository creates a new instance of IFarmRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIFarmRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IFarmRepository {
	mock := &IFarmRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
