// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	models "boonmafarm/api/pkg/models"

	mock "github.com/stretchr/testify/mock"
)

// IFeedPriceHistoryRepository is an autogenerated mock type for the IFeedPriceHistoryRepository type
type IFeedPriceHistoryRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: feedPriceHistory
func (_m *IFeedPriceHistoryRepository) Create(feedPriceHistory *models.FeedPriceHistory) (*models.FeedPriceHistory, error) {
	ret := _m.Called(feedPriceHistory)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.FeedPriceHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.FeedPriceHistory) (*models.FeedPriceHistory, error)); ok {
		return rf(feedPriceHistory)
	}
	if rf, ok := ret.Get(0).(func(*models.FeedPriceHistory) *models.FeedPriceHistory); ok {
		r0 = rf(feedPriceHistory)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.FeedPriceHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(*models.FeedPriceHistory) error); ok {
		r1 = rf(feedPriceHistory)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FirstByQuery provides a mock function with given fields: query, args
func (_m *IFeedPriceHistoryRepository) FirstByQuery(query interface{}, args ...interface{}) (*models.FeedPriceHistory, error) {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for FirstByQuery")
	}

	var r0 *models.FeedPriceHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}, ...interface{}) (*models.FeedPriceHistory, error)); ok {
		return rf(query, args...)
	}
	if rf, ok := ret.Get(0).(func(interface{}, ...interface{}) *models.FeedPriceHistory); ok {
		r0 = rf(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.FeedPriceHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}, ...interface{}) error); ok {
		r1 = rf(query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TakeAll provides a mock function with given fields: feedCollectionId
func (_m *IFeedPriceHistoryRepository) TakeAll(feedCollectionId int) (*[]models.FeedPriceHistory, error) {
	ret := _m.Called(feedCollectionId)

	if len(ret) == 0 {
		panic("no return value specified for TakeAll")
	}

	var r0 *[]models.FeedPriceHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*[]models.FeedPriceHistory, error)); ok {
		return rf(feedCollectionId)
	}
	if rf, ok := ret.Get(0).(func(int) *[]models.FeedPriceHistory); ok {
		r0 = rf(feedCollectionId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]models.FeedPriceHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(feedCollectionId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TakeById provides a mock function with given fields: id
func (_m *IFeedPriceHistoryRepository) TakeById(id int) (*models.FeedPriceHistory, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for TakeById")
	}

	var r0 *models.FeedPriceHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*models.FeedPriceHistory, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *models.FeedPriceHistory); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.FeedPriceHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: feedPriceHistory
func (_m *IFeedPriceHistoryRepository) Update(feedPriceHistory *models.FeedPriceHistory) error {
	ret := _m.Called(feedPriceHistory)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.FeedPriceHistory) error); ok {
		r0 = rf(feedPriceHistory)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIFeedPriceHistoryRepository creates a new instance of IFeedPriceHistoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIFeedPriceHistoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IFeedPriceHistoryRepository {
	mock := &IFeedPriceHistoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
